# Generated by Django 3.1.5 on 2021-12-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
