# Generated by Django 3.1.5 on 2021-12-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211224_1713'),
        ('alerts', '0002_auto_20211223_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.host'),
        ),
    ]
