# Generated by Django 3.1.5 on 2021-12-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20211224_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='source_name',
            new_name='source_id',
        ),
    ]
