# Generated by Django 3.1.5 on 2021-12-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20211225_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
