# Generated by Django 3.1.5 on 2021-12-27 15:51

import alerts.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211225_0116'),
        ('alerts', '0005_auto_20211225_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='data',
            field=models.JSONField(blank=True, default=alerts.models.get_default_alert_data, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.host'),
        ),
    ]
