# Generated by Django 3.1.5 on 2021-09-11 15:54

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('host_os_type', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], max_length=10)),
                ('host_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=255)),
                ('date_registered', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(default=api.models.get_initial_host_settings)),
                ('program_info', models.TextField(blank=True, null=True)),
                ('process_info', models.TextField(blank=True, null=True)),
                ('password_info', models.TextField(blank=True, null=True)),
                ('privesc_info', models.TextField(blank=True, null=True)),
                ('exploit_info', models.TextField(blank=True, null=True)),
                ('system_info', models.TextField(blank=True, null=True)),
                ('network_info', models.TextField(blank=True, null=True)),
                ('nmap_info', models.TextField(blank=True, null=True)),
                ('eventlog_info', models.TextField(blank=True, null=True)),
                ('schedtask_info', models.TextField(blank=True, null=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('online_status', models.BooleanField(default=False)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
