# Generated by Django 3.1.5 on 2021-09-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_host_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_health',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
