# Generated by Django 3.1.5 on 2021-12-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211224_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='eventlog_info',
            field=models.JSONField(blank=True, default={'eventlog_info': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='exploit_info',
            field=models.JSONField(blank=True, default={'exploit_info': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='network_info',
            field=models.JSONField(blank=True, default={'network_info': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='nmap_info',
            field=models.JSONField(blank=True, default={'nmap_info': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='password_info',
            field=models.JSONField(blank=True, default={'password_info': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='privesc_info',
            field=models.JSONField(blank=True, default={'privesc_info': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='process_info',
            field=models.JSONField(blank=True, default={'process_info': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='program_info',
            field=models.JSONField(blank=True, default={'program_info': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='schedtask_info',
            field=models.JSONField(blank=True, default={'schedtask_info': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='system_info',
            field=models.JSONField(blank=True, default={'system_info': ''}, null=True),
        ),
    ]
