# Generated by Django 3.1.5 on 2022-01-05 16:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211225_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='eventlog_info',
            field=models.JSONField(blank=True, default=api.models.get_default_eventlog_info, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='exploit_info',
            field=models.JSONField(blank=True, default=api.models.get_default_exploit_info, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='network_info',
            field=models.JSONField(blank=True, default=api.models.get_default_network_info, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='nmap_info',
            field=models.JSONField(blank=True, default=api.models.get_default_nmap_info, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='password_info',
            field=models.JSONField(blank=True, default=api.models.get_default_password_info, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='privesc_info',
            field=models.JSONField(blank=True, default=api.models.get_default_privesc_info, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='process_info',
            field=models.JSONField(blank=True, default=api.models.get_default_process_info, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='program_info',
            field=models.JSONField(blank=True, default=api.models.get_default_program_info, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='schedtask_info',
            field=models.JSONField(blank=True, default=api.models.get_default_schedtask_info, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='system_info',
            field=models.JSONField(blank=True, default=api.models.get_default_system_info, null=True),
        ),
    ]
